# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAutopurchasetest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_autopurchasetest(self):
    self.driver.get("https://shinygaragemalta-594b33247f63.herokuapp.com/")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.ID, "Cleaning-Products-link").click()
    self.driver.find_element(By.LINK_TEXT, "Interior").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-sm-6:nth-child(3) .card-img-top").click()
    self.driver.find_element(By.CSS_SELECTOR, "#increment-qty_64 > .icon").click()
    self.driver.find_element(By.CSS_SELECTOR, "#increment-qty_64 > .icon").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#increment-qty_64 > .icon")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").click()
    self.driver.find_element(By.ID, "Cleaning-Products-link").click()
    self.driver.find_element(By.LINK_TEXT, "All Cleaning Products").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-sm-6:nth-child(21) .card-img-top").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-plus").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".fa-plus")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-uppercase:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-right > .btn-black").click()
    self.driver.find_element(By.ID, "id_full_name").click()
    self.driver.find_element(By.ID, "id_full_name").click()
    element = self.driver.find_element(By.ID, "id_full_name")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "id_full_name").send_keys("Test")
    self.driver.find_element(By.ID, "id_email").send_keys("test@gmail")
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").click()
    element = self.driver.find_element(By.ID, "id_email")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("test@gmail.com")
    self.driver.switch_to.frame(1)
    self.driver.find_element(By.NAME, "cardnumber").click()
    self.driver.find_element(By.NAME, "cardnumber").send_keys("4242 4242 4242 4242")
    self.driver.find_element(By.NAME, "exp-date").send_keys("04 / 24")
    self.driver.find_element(By.NAME, "cvc").send_keys("242")
    self.driver.find_element(By.NAME, "postal").send_keys("42424")
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, "#submit-button > .font-weight-bold").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-uppercase").click()
  
